version: "3.7"

services:
  frontend:
    image: node-frontend
    environment:
      DATABASE_HOST: backend
    networks:
      - private-net
    ports:
      - 8080:9001
  backend:
    image: node-backend
    networks:
      - private-net

networks:
  private-net:
